python main.py --model hamida --dataset IndianPines_FastICA-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP-Split_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_FastICA-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP-Split_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_FastICA-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP-Split_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
