python main.py --model hamida --dataset Salinas_AE1_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE1_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE1_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE1_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset Salinas_AE2_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE2_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE2_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE2_8 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset Salinas_AE1_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE1_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE1_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE1_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset Salinas_AE2_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE2_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE2_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE2_15 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset Salinas_AE1_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE1_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE1_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE1_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset Salinas_AE2_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset Salinas_AE2_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset Salinas_AE2_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset Salinas_AE2_30 --training_sample 0.7 --patch_size 7 --epoch 30 --cuda 0
