python main.py --model hamida --dataset IndianPines_PCA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_PCA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_PCA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_PCA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_FastICA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Corr_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Corr_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Corr_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Corr_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_8 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_PCA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_PCA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_PCA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_PCA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_FastICA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Corr_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Corr_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Corr_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Corr_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_15 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_PCA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_PCA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_PCA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_PCA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_FastICA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_FastICA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_FastICA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_FastICA_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_UMAP_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_UMAP_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_UMAP_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_UMAP_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Corr_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Corr_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Corr_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Corr_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model hamida --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model li --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model mou --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
python main.py --model paoletti --dataset IndianPines_Var_30 --training_sample 0.7  --batch_size 20 --patch_size 7 --epoch 30 --cuda 0
